Create cronjob-ad-group-sync.yml
redhat-cop/openshift-management pull request #21
Opened 2018-02-13 18:03 UTC by lnicholson

Active Directory and LDAP function differently with Openshift.  Created a dedicated Active Directory Yaml.

#### What is this PR About?
This template can be used specifically for Active Directory, instead of heavily modifying the LDAP template and them executing on an OCP cluster.

#### How do we test this?
The instantiate template steps should suffice to test that the template is useful.  Just in case, below is the steps:

```
oc process -f jobs/cronjob-ldap-group-sync.yml \
  -p NAMESPACE="<project name from previous step>"
  -p LDAP_URL="ldap://idm-2.etl.rht-labs.com:389" \
  -p LDAP_BIND_DN="uid=ldap-user,cn=users,cn=accounts,dc=myorg,dc=example,dc=com" \
	-p LDAP_BIND_PASSWORD="password1" \
	-p LDAP_GROUPS_SEARCH_BASE="cn=groups,cn=accounts,dc=myorg,dc=example,dc=com" \
	-p LDAP_GROUPS_FILTER="(&(objectclass=ipausergroup)(memberOf=cn=ose_users,cn=groups,cn=accounts,dc=myorg,dc=example,dc=com))" \
	-p LDAP_USERS_SEARCH_BASE="cn=users,cn=accounts,dc=myorg,dc=example,dc=com" \
	| oc create -f- 
```

cc: @redhat-cop/day-in-the-life-ops

2018-03-29 19:46 UTC, oybed requested changes
One minor comment

2018-03-29 19:46 UTC, oybed commented on jobs/cronjob-ad-group-sync.yml
> +  apiVersion: "batch/v2alpha1"
With OpenShift v3.9, this is now 'too old' - please update to `batch/v1beta1`

2018-04-11 09:24 UTC, makentenza commented on jobs/cronjob-ad-group-sync.yml
> +                  - "oc adm groups sync --sync-config=/etc/config/ldap-group-sync.yaml --confirm"
Update this line to prevent jobs respawning. Check #24

2018-08-11 16:28 UTC, oybed commented
@lnicholson Any updates on this one? Would like to get it merged. Please let us know if you can incorporate the changes. If not, we'll most likely just close it out soon.

2018-10-30 15:49 UTC, oybed commented
Closing due to inactivity - please re-open if still needed

2018-10-30 15:49 UTC, closed without merging