Improved image pruning scheduledjob and added scheduledjob to prune builds and deployments
redhat-cop/openshift-management pull request #3
Opened 2017-04-03 01:09 UTC by sabre1041

#### What is this PR About?
Adds scheduled job to prune builds and deployments

Note: `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` are not currently implemented in OCP, but will be in future release. Those fields are currently ignored

#### How do we test this?
Add the template to the OpenShift cluster and instantiate the template. Additional information can be found in the README

cc: @redhat-cop/day-in-the-life-ops @etsauer @oybed

2017-04-04 15:30 UTC, makentenza requested changes
@sabre1041 some changes I'd suggest for this, just to facilitate the final users, let's say Customers, to use this repository. This could be clear to be used from the Web Console, but I think this could be more clear if we add more instructions when this is created using a terminal.

This is fine "Note: Some templates require additional parameters to be specified. Be sure to review each specific template contents prior to instantiation", but it'd better if we add the following to the README file.

1.-  A particular example for each case, I mean, how to create the job for images, builds and deployments
2.- While creating the job for builds/deployment this will fail (same name) unless we specify in the creation the name of the job. Another option could be to auto complete the "JOB_NAME" var with the info from "PRUNE_TYPE".

2017-04-05 04:41 UTC, sabre1041 commented
@makentenza thanks for the review. a few comments

1. My fear with putting in examples for each use case is that it will become difficult to manage as the library grows. Also, when there are modifications, changes need to be made in both places. I was hoping the generic example provided could be applied for the majority of implementations. In addition, the user can execute `oc describe <template>` to find out the specific parameters available in the template

2. Good idea. Updated the job name to be `<JOB_NAME>-<PRUNE_TYPE>` as suggested

2017-04-05 09:13 UTC, makentenza commented
@sabre1041 agree. If we add more resources the maintenance would be harder.

There is another thing we need to solve now. The 'edit' cluster role is not enough to list all the images:

```
mak@MakF:~/GIT/openshift-management/jobs (pr3)$ oc logs -f scheduledjob-prune-images-1859749706-zr6yl
Error from server: User "system:serviceaccount:prune-jobs:pruner" cannot list all images in the cluster
```
```
mak@MakF:~/GIT/openshift-management/jobs (pr3)$ oc describe clusterPolicyBindings |grep -A4 edit
RoleBinding[edit]:						 
								Role:			edit
								Users:			<none>
								Groups:			<none>
								ServiceAccounts:	prune-jobs/pruner
								Subjects:		<none>

```
```
mak@MakF:~/GIT/openshift-management/jobs (pr3)$ oc adm policy who-can list images
Namespace: prune-jobs
Verb:      list
Resource:  images

Users:  mak
        system:admin
        system:serviceaccount:infra-monitor:metrics
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:openshift-infra:heapster
        system:serviceaccount:openshift-infra:namespace-controller
        system:serviceaccount:prometheus:metrics

Groups: system:cluster-admins
        system:cluster-readers
        system:masters
```
According to this, ServiceAccount pruner must be added the roles cluster-admin or cluster-reader

2017-04-05 13:31 UTC, sabre1041 commented
@makentenza good catch on the permissions side. I updated the README

2017-04-05 13:41 UTC, makentenza approved these changes
Looks good to me

2017-04-05 14:10 UTC, merged