add helm charts for all jobs
redhat-cop/openshift-management pull request #49
Opened 2020-04-01 23:14 UTC by pcarney8

#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/casl

2020-04-03 15:45 UTC, jkupferer requested changes

2020-04-03 15:45 UTC, jkupferer commented on charts/cluster-descheduler/templates/configmap.yaml
> +  policy.yaml: "apiVersion: descheduler/v1alpha1\nkind: DeschedulerPolicy\nstrategies:\n
Can we use a YAML block quote here?
```
data:
  policy.yaml: |
    apiVersion: descheduler/v1alpha1
    ...
```

2020-04-17 15:38 UTC, pcarney8 commented on charts/cluster-descheduler/templates/configmap.yaml
> +  policy.yaml: "apiVersion: descheduler/v1alpha1\nkind: DeschedulerPolicy\nstrategies:\n
updated.

2020-05-11 15:25 UTC, mcanoy commented on charts/cluster-descheduler/Chart.yaml
> +  and dupliacate pod placements
duplicate typo

2020-06-19 17:59 UTC, oybed approved these changes
LGTM - any nitpick will be addressed in follow-up

2020-06-19 17:59 UTC, merged