Add etcd procedures repo
redhat-cop/openshift-management pull request #5
Opened 2017-05-02 21:46 UTC by makentenza

#### What is this PR About?
Resources to operate an etcd Cluster for Openshift. This repository will contain different documents and playbooks to operate etcd. This PR is covering the first procedure, scale up an etcd Cluster. A document with detailed steps is provided and a playbook is included as well in order to automate the process.

#### How do we test this?
Manual steps: Follow instructions from docs/README.md
Automatic playbook: Follow instructions from playbooks/README.md

cc: @redhat-cop/day-in-the-life-ops

2017-05-08 03:48 UTC, sabre1041 requested changes
@makentenza Performed a review of the documentation and not yet of the steps/playbooks.

I really like this as it is really needed. Since there is mixed document format (markdown vs asciidoc), it might make sense that the entire repository migrate to asciidoc. thoughts?

2017-05-08 03:48 UTC, sabre1041 commented on etcd-procedures/README.md
> +* Add new member to an existing Cluster
Add links to sub pages as necessary

2017-05-08 03:48 UTC, sabre1041 commented on etcd-procedures/docs/README.md
> +* **add_etcd_node.adoc**: this document can be used to **scale up** an existing etcd Cluster with new member(s). This is only aplicable to containerized etcd Clusters.
Add link to `add_etcd_node.adoc`

2017-05-08 03:48 UTC, sabre1041 commented on etcd-procedures/docs/add_etcd_node.adoc
> +==== From one of the existing etcd Nodes, get the etcd container image version we need to run
Would you be able to provide context into what the commands that are performing?

2017-05-08 03:48 UTC, sabre1041 commented on etcd-procedures/playbooks/README.md
> +* A new entry called **new_etcd** under [OSEv3:children] group
Would a sample inventory be more helpful?

2017-05-08 03:48 UTC, sabre1041 commented on etcd-procedures/playbooks/README.md
> +* **etcd_scaleup.yml**: automatically scales up an existing etcd cluster with a new member included in [new_etcd] group. This is only aplicable to containerized etcd Clusters.
Add link

2017-05-10 17:04 UTC, makentenza commented on etcd-procedures/docs/add_etcd_node.adoc
> +==== From one of the existing etcd Nodes, get the etcd container image version we need to run
Do you mean the below commands?

Containerized etcd:
  # docker ps | grep etcd | awk {'print $2'}
Package etcd:
  # etcd --version | grep etcd | awk {'print "registry.access.redhat.com/rhel7/etcd:"$3'}

2017-05-19 09:55 UTC, makentenza commented
I'm closing this PR as we are moving this to openshift-toolkit as discussed

https://github.com/redhat-cop/openshift-toolkit/pull/7

2017-05-19 09:55 UTC, closed without merging