Prune Tekton PipelineRun
redhat-cop/openshift-management pull request #76
Opened 2020-10-21 09:03 UTC by mvmaestri

#### What is this PR About?
This is a cronjob to prune tekton pipelineruns defining a number to keep

#### How do we test this?
helm template -f charts/cronjob-prune-tekton-pipelinerun/values.yaml charts/cronjob-prune-tekton-pipelinerun | oc apply -f-

cc: @redhat-cop/casl

2020-10-23 14:31 UTC, pabrahamsson requested changes
Thank you @mvmaestri, this looks good just two small comments inline.

2020-10-23 14:31 UTC, pabrahamsson commented on charts/cronjob-prune-tekton-pipelinerun/templates/rolebinding.yaml
> +- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.job_service_account }}
Can you change the name of this file to `clusterrolebinding.yaml` to reflect that it is indeed a ClusterRoleBinding?

2020-10-23 14:31 UTC, pabrahamsson commented on charts/cronjob-prune-tekton-pipelinerun/templates/cronjob.yaml
> +              image: ghcr.io/ctron/kubectl:latest
I would suggest using values for the image and tag similar to how other cronjobs in this repo is doing this.
```
image: {{ .Values.image }}:{{ .Values.image_tag }}
```
I would also suggest to use `quay.io/openshift/origin-cli:4.5` as the image/tag (it has both `oc` and `kubectl`).

2020-10-26 12:20 UTC, mvmaestri commented on charts/cronjob-prune-tekton-pipelinerun/templates/cronjob.yaml
> +              image: ghcr.io/ctron/kubectl:latest
✅

2020-10-26 12:20 UTC, mvmaestri commented on charts/cronjob-prune-tekton-pipelinerun/templates/rolebinding.yaml
> +- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.job_service_account }}
✅

2020-10-26 12:22 UTC, mvmaestri commented
Done @pabrahamsson

2020-10-26 14:21 UTC, pabrahamsson approved these changes
Thank you @mvmaestri LGTM

2020-10-26 14:22 UTC, merged