Update roles for jobs
redhat-cop/openshift-management pull request #8
Opened 2017-06-01 19:43 UTC by etsauer

#### What is this PR About?
Enhanced the ldap sync job template to include tightly scope roles.

#### How do we test this?
Follow the LDAP Group Sync section of `jobs/README.md`

cc: @redhat-cop/day-in-the-life-ops

2017-06-02 14:35 UTC, sabre1041 requested changes
Looks good. Added a few minor items

2017-06-02 14:35 UTC, sabre1041 commented on jobs/README.md
> +The [scheduledjob-ldap-group-sync.json](scheduledjob-ldap-group-sync.json) facilitates routine [LDAP Group Synchronization](https://docs.openshift.com/container-platform/3.4/install_config/syncing_gr
Can the latest docs be referenced?

2017-06-02 14:35 UTC, sabre1041 commented on jobs/README.md
> +This template makes several assumptions about your LDAP architecture and intentions of your group sync process, and is meant to showcase a common use case seen in the field. In this case, we use a to
Maybe a callout that customizations will most likely be required by the end user

2017-06-03 02:30 UTC, sabre1041 commented
@etsauer I validated the functionality. But as discussed offline, we probably need to call out the fact that this example _must_ be created in a project called `cluster-ops` as the ClusterRoleBinding has this value hardcoded. 

OpenShift 3.7 is targeted to have the functionality to have the current namespace parameter present ([Trello](https://trello.com/c/zcRQFri0/916-(2)-%24%7Bnamespace%7D-template-parameter-%5Btemplates%5D))

2017-06-03 02:55 UTC, etsauer commented
@sabre1041 done.

2017-06-03 02:56 UTC, sabre1041 approved these changes

2017-06-03 02:56 UTC, merged